spring:
  application:
    name: spring-mcp
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: prajesh-ananthanv-mcp
        version: 1.0.0
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"